"use strict";
const bcrypt = require("bcryptjs");

module.exports = {
	async up(queryInterface, Sequelize) {
		return queryInterface.bulkInsert("users", [
			{
				id: 1,
				username: "oakley",
				email: "oakley@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 1,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 2,
				username: "Ching",
				email: "ching@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "FEMALE",
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 3,
				username: "wanchai",
				email: "wanchai@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 4,
				username: "premmimi",
				email: "premmimi@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 5,
				username: "ormzaap",
				email: "ormzaap@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "FEMALE",
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 6,
				username: "tenz",
				email: "tenz@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 3,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 7,
				username: "shazam",
				email: "shazam@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 3,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 8,
				username: "dapr",
				email: "dapr@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 3,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 9,
				username: "sick",
				email: "sick@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 3,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 10,
				username: "nats",
				email: "nats@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 5,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 11,
				username: "sheydos",
				email: "sheydos@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "FEMALE",
				team_id: 5,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 12,
				username: "foxz",
				email: "foxz@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "FEMALE",
				team_id: 2,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 13,
				username: "pooh1tap",
				email: "pooh@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "FEMALE",
				team_id: 2,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 14,
				username: "patiphan",
				email: "patiphan@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "FEMALE",
				team_id: 2,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 15,
				username: "chalalala",
				email: "chalalala@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 4,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 16,
				username: "superbuss",
				email: "superbuss@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 4,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 17,
				username: "lammysnax",
				email: "lammysnax@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 4,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 18,
				username: "johnolsen",
				email: "johnolsen@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 4,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 19,
				username: "PTC",
				email: "ptc@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 4,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 20,
				username: "zues",
				email: "zues@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 2,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 21,
				username: "crws",
				email: "crws@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 2,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 22,
				username: "sscary",
				email: "sscary@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 2,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 23,
				username: "sushiboys",
				email: "sushiboys@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 2,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 24,
				username: "zombs",
				email: "zombs@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				team_id: 2,
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 25,
				username: "grace",
				email: "grace@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "FEMALE",
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 26,
				username: "pymmy",
				email: "pymmy@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "FEMALE",
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 27,
				username: "pakko",
				email: "pakko@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "FEMALE",
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 28,
				username: "boonyen",
				email: "boonyen@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 29,
				username: "porch",
				email: "porch@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "MALE",
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 30,
				username: "patty",
				email: "patty@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "FEMALE",
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				id: 31,
				username: "coalforchristmas",
				email: "coalforchristmas@gmail.com",
				password: await bcrypt.hash("1234", 10),
				gender: "FEMALE",
				birth_date: new Date(),
				created_at: new Date(),
				updated_at: new Date(),
			},
		]);
	},

	async down(queryInterface, Sequelize) {
		await queryInterface.bulkDelete("users", null, {});
	},
};
